### PR TITLE
Make set_nonce py3 compatible

### PR DESCRIPTION
**Pull request by alimpon**

### CODE REVIEW

**Review by ndfong — APPROVED** [review]
LGTM, this is for [FRAUDENG-364](https://jira.team.affirm.com/browse/FRAUDENG-364) right? Has nobody else encountered this issue before?

**Comment by msherry** [comment]
Any tests for this change, either ensuring backward compatibility if necessary, or demonstrating the problem that it fixes?

**Comment by alimpon** [comment]
> Any tests for this change, either ensuring backward compatibility if necessary, or demonstrating the problem that it fixes?

@msherry I ran both the py2 and py3 versions of the client code that calls into this package, the tests still passed in py2 and got past this problem in py3.

**Comment by msherry** [comment]
> @msherry I ran both the py2 and py3 versions of the client code that calls into this package, the tests still passed in py2 and got past this problem in py3.

Can you add appropriate test cases to *this* package, though? We shouldn't depend on external packages to do our testing, IMO.

**Pull request merged**
